server:
  host: "0.0.0.0"
  port:
    grpc: 8080
    metric: 8081
    gw: 8082
    files: 8083
auth_key: "super-duper-secret-key-qwertyuio"
dev_mode: true
file_store:
  secure: false
  endpoint: "minio:9000"
  access_key: "test_svc"
  secret_key: "test_pass"
db:
  migrate_dir: "migrate"
  driver: "postgres"
  postgres: "postgres://user_svc:user_pass@postgres:5432/user_db?sslmode=disable"

